function h = annotate_best_point(ax, x, y, labelText, color)
%ANNOTATE_BEST_POINT Add a compact callout label to a key point.

if nargin < 5 || isempty(color)
    color = [0.15 0.15 0.15];
end

hold(ax, 'on');
plot(ax, x, y, 'p', ...
    'MarkerSize', 12, ...
    'MarkerFaceColor', color, ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 1.0, ...
    'HandleVisibility','off');

h = text(ax, x, y, "  " + string(labelText), ...
    'FontSize', 10.5, ...
    'FontName', 'Times New Roman', ...
    'Color', color, ...
    'VerticalAlignment', 'middle', ...
    'BackgroundColor', 'w', ...
    'Margin', 3, ...
    'EdgeColor', lighten_color(color, 0.65));

end
